# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='size',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
