# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_album_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-created_time', '-updated_time']},
        ),
    ]
