# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 07:21
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170222_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=blog.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='album',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
