# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='album',
            new_name='photo_album',
        ),
    ]
